sudo: false
language: python
cache: pip
python:
  - "3.4"
install:
  - pip install -r requirements-test.txt
script:
  - py.test -vvv --cov database_sanitizer --cov-report=term-missing
after_success:
  - curl -s https://codecov.io/bash | bash

